name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        env:
          APIURL: ${{secrets.API_URL}}
          KEY_IDENTITY: ${{secrets.KEY_IDENTITY}}
          KEY_CREDENTIAL: ${{secrets.KEY_CREDENTIAL}}
